language: python
python:
  - "3.8.6"

sudo: required

services:
  - docker

before_install:
  - sudo service mysql stop
  - while sudo lsof -Pi :3306 -sTCP:LISTEN -t; do sleep 1; done
  - sudo docker-compose up -d --build
 

before_script: pip3 install docker-compose

script:
  - docker-compose run web sh -c "python3 manage.py test"

after_success:
  #log in Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take builtin images and push to Docker hub
  - docker push sujata1003/ecommerce

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  region: "us-west-2"
  app: "ecomm-docker-web"
  env: "Ecommdockerweb-env"
  bucket_name: "elasticbeanstalk-us-west-2-677585450238"
