language: python
python:
  - "3.8.6"

sudo: required

services:
  - docker

before_install:
  - sudo service mysql stop
  - while sudo lsof -Pi :3306 -sTCP:LISTEN -t; do sleep 1; done
  - sudo docker-compose up -d --build
  - sudo docker exec -it web bash -c "python3 manage.py test"

before_script: pip3 install docker-compose

script:
  - docker-compose run web sh -c "python3 manage.py test"
