language: python
python:
  - "3.8.6"

services:
  - docker

before_script: - pip3 install docker-compose
               - sudo docker-compose build

script:
  - docker-compose run web sh -c "python3 manage.py test"
