language: python
python:
  - "3.8.6"

services:
  - docker

before_script: pip3 install docker-compose

script:
  - docker-compose run web python3 manage.py test
  
deploy:
    provider: script
    script: bash docker_push.sh
    skip_cleanup: true
    on:
        branch: master
