version: '3'
services:
  db:
    image: mysql:5.7.31
    ports:
      - '3306:3306'
      
    restart: always
    environment:
      #- MYSQL_HOST=172.19.0.3
      #- MYSQL_PORT=3306
      - MYSQL_ROOT_PASSWORD=Root@123
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Root@123
      - MYSQL_DATABASE=ecommDB


  web:
    build: .
    ports:
      - "80:8000"
    
    command: ["/app/wait-for-mysql.sh", "db", "3306", "Root@123", "ecommDB", "--", "python3", "manage.py", "runserver", "0.0.0.0:8000"]
    #command: ["/app/wait-for-mysql.sh", "db", "3306", "Root@123", "ecommDB"]
    #command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py createsuperuserwithpassword --username admin1 --password admin1 --email admin1@gmail.com  && python3 manage.py runserver 0.0.0.0:8000"
    #command: bash -c "python3 manage.py runserver 0.0.0.0:8000"

    #command: bash -c  "python3 ./app/wait-for-mysql.sh db 3306 Root@123 ecommDB && python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py createsuperuserwithpassword --username admin1 --password admin1 --email admin1@gmail.com  && python3 manage.py runserver 0.0.0.0:8000"


    depends_on:
      - db

